<?php
session_start();
$conn = new mysqli("localhost","root",12345,"healthcare");
if(mysqli_connect_errno()){
    die("Connection failed". mysqli_connect_error());
}
if($_SERVER["REQUEST_METHOD"] == "POST"){
    $doctor_id = $_POST["doctor_id"];
    $patient_id = $_POST["patient_id"];
    $invoice_details = $_POST["invoice_details"];
    $amount = $_POST["amount"];
    $status = "pending";
    $sql = "insert into billing (doctor_id,patient_id,invoice_details,amount,status) values ('$doctor_id','$patient_id','$invoice_details','$amount','$status')";
    $result = mysqli_query($conn, $sql);
}
$id = $_SESSION["user_id"];
$query = "select * from billing where doctor_id in (select doctor_id from doctor where user_id = '$id')";
$result = mysqli_query($conn, $query);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Billing and Invoice</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        
        body {
            background-color: #f8f9fa;
        }
        .container {
            margin-top: 50px;
        }
        .form-container {
            background-color: #ffffff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            animation: fadeIn 1s ease-out;
        }
        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }
        .table-container {
            margin-top: 30px;
            animation: slideIn 1s ease-out;
        }
        @keyframes slideIn {
            from { transform: translateY(-20px); opacity: 0; }
            to { transform: translateY(0); opacity: 1; }
        }
    </style>
    </head>
<body>
    <div class="container">
        <div class="form-container">
            <form action="billing.php" method="post">
                <div class="mb-3 mt-3">
                    <label for="doctor_id">Doctor ID:</label>
                    <input type="text" name="doctor_id" required><br>
                </div>
                <div class="mb-3 mt-3">
                    <label for="patient_id">Patient ID:</label>
                    <input type="text" name="patient_id" required><br>
                </div>
                <div class="mb-3 mt-3">
                    <label for="invoice_details">Invoice Details:</label>
                    <textarea name="invoice_details" rows="4" required></textarea><br>
                </div>
                <div class="mb-3 mt-3">
                    <label for="amount">Amount:</label>
                    <input type="number" step="0.01" name="amount" required><br>
                </div>
                <input type="submit" value="Create Billing Record">
            </form>
        </div>
    </div>
    <div class="container">
        <div class="conatiner table-container">
            <h2 class="mt-5">List of Invoices Generated by You</h2>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Billing Id</th>
                        <th>Doctor Id</th>
                        <th>Patient Id</th>
                        <th>Invoice Details</th>
                        <th>Amount</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if(mysqli_num_rows($result) > 0){
                        while($row = mysqli_fetch_assoc($result)){
                            echo "<tr>";
                            echo "<td>" . $row['billing_id'] . "</td>";
                            echo "<td>" . $row['doctor_id'] . "</td>";
                            echo "<td>" . $row['patient_id'] . "</td>";
                            echo "<td>" . $row['invoice_details'] . "</td>";
                            echo "<td>" . $row['amount'] . "</td>";
                            echo "<td>" . $row['status'] . "</td>";
                            echo "</tr>";
                        }
                    }else{
                        echo "<tr><td colspan='6'>0 Results Found...</td></tr>";
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>